server:
  port: 80
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/expensiveshop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Hongkong
    username: root
    password: 12345678

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shop:
  cors:
    allowOrigin: http://www.life-runner.com
    allowCredentials: true
    allowedMethod: '*'
    allowedHeader: '*'