server:
  port: 8088
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/expensiveshop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=Hongkong
    username: root
    password: 12345678
  # redis 单机节点配置
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#    # password: 12345678
  # redis 主备配置
  redis:
    sentinel:
      master: 127.0.0.1
      nodes: 192.168.1.100,192.168.1.101,192.168.1.102
    database: 0
    password: 12345678

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shop:
  cors:
    allowOrigin: http://localhost:8080
    allowCredentials: true
    allowedMethod: '*'
    allowedHeader: '*'